name=7Semi MCP4725
version=1.0.0
author=7Semi
maintainer=7Semi <info@7semi.com>
sentence=Arduino Library for the 7semi MCP4725 12-bit I2C DAC Module.
paragraph=Supports 12-bit analog output using MCP4725 over I2C. Features fast mode (no EEPROM write), configurable I2C speed, and support for multiple wire ports.
category=Signal Input/Output
url=https://github.com/7semi-solutions/7Semi-MCP4725
architectures=*
includes=7Semi_MCP4725.h
